# Generated by Django 5.2.13 on 2026-04-16 04:18

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del platillo.', max_length=200)),
                ('categoria', models.CharField(choices=[('Desayuno', 'Desayuno'), ('Comida', 'Comida'), ('Cena', 'Cena'), ('Postre', 'Postre'), ('Bebida', 'Bebida')], help_text='Categoría de la receta.', max_length=50)),
                ('imagen', cloudinary.models.CloudinaryField(help_text='URL de la imagen gestionada en Cloudinary.', max_length=255, verbose_name='imagen')),
                ('instrucciones', models.TextField(help_text='Paso a paso de la preparación.')),
                ('ingredientes', models.JSONField(help_text='Lista de ingredientes necesarios guardados como estructura JSON.')),
                ('porciones', models.IntegerField(help_text='Cantidad de personas/porciones.')),
                ('tiempo_preparacion', models.CharField(help_text='Tiempo estimado (ej: "30 min").', max_length=50)),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['-id'],
            },
        ),
    ]
