# Generated by Django 5.2.13 on 2026-06-01 01:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='imagen',
            field=cloudinary.models.CloudinaryField(help_text='URL de la imagen gestionada en Cloudinary.', max_length=255, verbose_name='img'),
        ),
    ]
