# Generated by Django 5.2.13 on 2026-06-05 04:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='URL de la imagen gestionada en Cloudinary.', max_length=255, null=True, verbose_name='img'),
        ),
    ]
